name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    strategy:
      fail-fast: false # otherwise a failing job cancels all other jobs.
      matrix:
        region: ['austin', 'boston', 'budapest', 'hyderabad', 'montreal']
    name: Validate Action (${{ matrix.region }})
    runs-on: [self-hosted, linux, x64, "${{ matrix.region }}" ]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # see: https://github.com/actions/checkout/issues/1048
      - name: Fix dubious ownership in repository
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Test Local Action
        id: test-action
        uses: ./          

      - name: Check outputs
        id: check-outputs
        run: |
          echo "SLT version installed: ${{ steps.test-action.outputs.slt-version }}"
          echo "SLT executable path : ${{ steps.test-action.outputs.slt-path }}"
          echo "conan_engine version installed: ${{ steps.test-action.outputs.conan-engine-version }}"
          echo "conan_engine executable path: ${{ steps.test-action.outputs.conan-engine-path }}"
          echo "conan version installed: ${{ steps.test-action.outputs.conan-version }}"
          echo "conan executable path: ${{ steps.test-action.outputs.conan-path }}"
